framework:
    default_locale: fr   
    translator:
        default_path: '%kernel.project_dir%/translations'

        providers: { }

        # Langue de secours si la traduction nâ€™existe pas
        fallbacks:
            - fr
